<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>cotf</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
	<UseWindowsForms>true</UseWindowsForms>
	<UseWPF>true</UseWPF>
	<LangVersion>11</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="cotf-remix\Game.cs" />
    <Compile Remove="cotf-remix\Program.cs" />
    <Compile Remove="cotf-remix\WorldGen\Factory\Keypad.cs" />
    <Compile Remove="cotf-remix\WorldGen\Factory\Tiles\ClosedMetalDoor.cs" />
    <Compile Remove="cotf-remix\WorldGen\Factory\Tiles\FactoryTile.cs" />
    <Compile Remove="cotf-remix\WorldGen\Factory\Tiles\MetalDoorOpen.cs" />
    <Compile Remove="cotf-remix\WorldGen\Factory\Tiles\MetalDoorOpening.cs" />
    <Compile Remove="cotf-remix\World\Lighting\Fog.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SharpDX" Version="4.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\REWD\REWD.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Content\Items\flask_mercury.rew">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Items\Jobs\Scroll_plague_nova.rew">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Projectiles\magno_javelin.rew">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Content\Sky_boss.rew">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Walls\magno_brickwall.rew">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Waters\LiquidMetalWaterfallStyle.rew">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Content\Waters\LiquidMetalWaterStyle.rew">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Content\Waters\LiquidMetalWaterStyle_Block.rew">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Content\Waters\LiquidMetalWaterStyle_Slope.rew">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Content\Waters\MagnoWaterfallStyle.rew">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Textures\background.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\Backgrounds\MapBGMagno.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\bg.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\chain.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\cinnabar_dagger.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\ClassIcon_UI.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\config_icons.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\fow.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\fow50.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\Ground\background.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\item0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\loot0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\npc0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\npc1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\pixel.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\projectile0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\scenery0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\Sky_1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\Sky_1_1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\Sky_1_2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\Sky_1_3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\Sky_3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\Sky_boss.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\small.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\temp.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\temp90.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\trap0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\Walls\wall1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\Walls\wall2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\Walls\wall3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Textures\Walls\wall4.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Content\Items\" />
  </ItemGroup>

</Project>
